### ISSUE TITLE
Results Page movie titles alignment

### ISSUE THREAD

**Issue by LeKinchi** [ShinValor/Binger#107]
The Layout of text on the search results page
![Screen Shot 2020-07-28 at 3 29 40 PM](https://user-images.githubusercontent.com/32843930/88712156-457c0580-d0e7-11ea-86c5-6f7c92a90fd3.png)

To Reproduce
1. Go to the page and search for a word that appears in a lot of movies

Expected behavior
The names of movies should be align either left or center But I think left is better

Other
I think the search bar is a bit too long

**Comment by ShinValor** [comment]
Do you know the cause of this?

I also think left is better.
Yea the search bar is little too long.

Make a story and submit PR if you can fix this. Thanks.
