### ISSUE TITLE
Movie Swiper image squashed

### ISSUE THREAD

**Issue by LeKinchi** [ShinValor/Binger#116]
**Describe the bug**
On the movie swiper, the image is being squashed.
<img width="655" alt="Screen Shot 2020-08-04 at 12 35 37 PM" src="https://user-images.githubusercontent.com/32843930/89320257-406f0700-d64f-11ea-939c-4900392bb835.png">

**To Reproduce**
1. Go to the Movie Swiper and start swiping (Make sure you are using safari)

**Additional Notes** 
It works on Safari

**Comment by ShinValor** [comment]
Seems like it happens in safari, firefox and etc.. But not in Chrome

**Comment by ShinValor** [comment]
https://github.com/ShinValor/Binger/pull/117
