### ISSUE TITLE
Node GitHub Action not running

### ISSUE THREAD

**Issue by ShinValor** [ShinValor/Binger#15]
Node GH Action not executing because the app/ is not at root directory. Need to cd into app to execute the build

**Comment by LeKinchi** [comment]
just edit the steps of that action workflow

**Comment by ShinValor** [comment]
> just edit the steps of that action workflow

Submit a PR for that then.

**Comment by ShinValor** [comment]
https://github.com/ShinValor/Binger/pull/27

**Comment by ShinValor** [comment]
https://github.com/ShinValor/Binger/pull/35
