### ISSUE TITLE
Google cloud trigger

### ISSUE THREAD

**Issue by junqili259** [ShinValor/Binger#76]
Google cloud trigger check still running. I don't know if it's suppose to do that but issuing in case.

https://user-images.githubusercontent.com/39481617/86552573-64d3a880-bf16-11ea-9442-be6c29ebdab3.png

**Comment by ShinValor** [comment]
Which branch is this

**Comment by ShinValor** [comment]
Nevermind, it's the dev branch

**Comment by ShinValor** [comment]
Make a PR to update the README.md (Unbold the contributor name). This should rerun the trigger, build and deploy. Maybe this will fix it. @junqili259
